title: Colour
context:
  categories:
    - name: Text
      colours:
        - hex: "#0B0C0C"
          sass: $text-colour
        - hex: "#6F777B"
          sass: $secondary-text-colour
        - hex: "#FFFFFF"
          sass: $page-colour
    - name: Links
      colours:
    - name: Backgrounds
      colours: