title: Radio buttons
label: Radio buttons
context:
  id: question
  questionText: Where do you live?
  options:
  -	radioText: Northern Ireland
    value: 1
  -	radioText: Isle of Man or the Channel Islands
    value: 2
  -	radioText: I am a British citizen living abroad
    value: 3
